[package]
name = "hprof-slurp"
version = "0.4.8"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
description = "JVM heap dump hprof file analyzer"
edition = "2021"

[dependencies]
nom = "7.1.1"
indicatif = "0.17.1"
clap = { version = "3.2.21", features = ["cargo"] }
indoc = "1.0.7"
ahash = "0.8.0"
thiserror = "1.0.34"
crossbeam-channel = "0.5.6"