[package]
name = "hprof-slurp"
version = "0.5.0"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
description = "JVM heap dump hprof file analyzer"
edition = "2021"

[dependencies]
nom = "7.1.1"
indicatif = "0.17.2"
clap = { version = "4.0.25", features = ["cargo"] }
indoc = "1.0.7"
ahash = "0.8.2"
thiserror = "1.0.37"
crossbeam-channel = "0.5.6"