[package]
name = "hprof-slurp"
version = "0.4.6"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
description = "JVM heap dump hprof file analyzer"
edition = "2021"

[dependencies]
nom = "7.1.1"
indicatif = "0.17.0-rc.11"
clap = { version = "3.2.14", features = ["cargo"] }
indoc = "1.0.6"
ahash = "0.7.6"
thiserror = "1.0.31"
crossbeam-channel = "0.5.6"